order:
    resource: "@OrderBundle/Resources/config/routing.yml"
    prefix:   /order

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
